module.exports = {
   cities: [
    'Å aÄ¾a', 
    'AbÃ©chÃ©', 
    'Abidjan', 
    'Abomey-Calavi', 
    'Abu Dhabi', 
    'Adamstown', 
    'Addis Ababa', 
    'Aden', 
    'Agenskalns', 
    'Agia Anna', 
    'Agrabad', 
    'Al Marj', 
    'Al Markh', 
    'Al Shamiya', 
    'Al Wakrah', 
    'Alajuelita', 
    'Aleksandriya', 
    'Almazah', 
    'Alofi', 
    'Ambanja', 
    'American Samoa', 
    'An Nhon', 
    'Anabar', 
    'Antananarivo', 
    'Antarctica', 
    'Apia', 
    'Ar Rawdah', 
    'Ar Rayyan', 
    'Arnan', 
    'Arroyo', 
    'Arusha', 
    'As Satwah', 
    'Ashgabat', 
    'Asmara', 
    'Atacames', 
    'Atafu Village', 
    'Aukra', 
    'Auning', 
    'Avarua', 
    'Awasa', 
    'BÃ©char', 
    'Bad Pirawarth', 
    'Balboa', 
    'Balenya', 
    'Balfour Town', 
    'Ballincollig', 
    'Bamako', 
    'Ban Hua Thale', 
    'Banana', 
    'Banatsko Novo Selo', 
    'Banda del Rio Sali', 
    'Bandar-e Khamir', 
    'Bangar', 
    'Bangui', 
    'Banino', 
    'Banjul', 
    'Barisal', 
    'Barrigada Village', 
    'Barva', 
    'Basseterre', 
    'Bath', 
    'Beau Bassin', 
    'Beira', 
    'Belhar', 
    'Belmopan', 
    'Benghazi', 
    'Berekua', 
    'Bestovje', 
    'Bingemma', 
    'Birgu', 
    'Birjand', 
    'Bishkek', 
    'Blantyre', 
    'Bluefields', 
    'Bobo-Dioulasso', 
    'Bodden Town', 
    'Boqueron', 
    'Borran-e Bala', 
    'Bosanska Dubica', 
    'Bougara', 
    'Brobyvaerk', 
    'Browns Town', 
    'Brownsweg', 
    'BuÃ±ol', 
    'Budva', 
    'Bujumbura', 
    'Bulawayo', 
    'Busteni', 
    'Cabreuva', 
    'Cabudare', 
    'Cacheu', 
    'Calkaya', 
    'Callao', 
    'Canelones', 
    'Canovanas', 
    'Cap-HaÃ¯tien', 
    'Capilla del Monte', 
    'Case-Pilote', 
    'Cassada Gardens', 
    'Castletown', 
    'Cave Hill', 
    'Chachapoyas', 
    'Chaiyaphum', 
    'Changi Village', 
    'Charlotte Amalie', 
    'Chekka', 
    'Cheongju-si', 
    'Chernolik', 
    'ChiÅŸinÄƒu', 
    'Chiconi', 
    'Chigore', 
    'Chihertey', 
    'Choa Chu Kang New Town', 
    'Choloma', 
    'Chotomow', 
    'Christiansted', 
    'Chuen Lung', 
    'Ciorescu', 
    'Ciudad Ayala', 
    'Ciudad Vieja', 
    'Clapham', 
    'Clarks', 
    'Cockburn Harbour', 
    'Cojusna', 
    'Collipulli', 
    'Comayagua', 
    'Comayaguela', 
    'Coppull', 
    'Cotoca', 
    'Cotonou', 
    'Crassier', 
    'Dakar', 
    'Dalvik', 
    'Darganata', 
    'Dauphin', 
    'Davy Hill', 
    'Dededo Village', 
    'Deryneia', 
    'Desenzano del Garda', 
    'Dik el Mehdi', 
    'Dili', 
    'Djibouti', 
    'Doha', 
    'Don Mueang', 
    'Dorp Nikiboko', 
    'Drumbo', 
    'Dubai', 
    'Dundrum', 
    'Durazno', 
    'Durbe', 
    'Durlesti', 
    'DurrÃ«s', 
    'Dushanbe', 
    'Ebene CyberCity', 
    'EckerÃ¶', 
    'Ehnen', 
    'El Barro', 
    'El Hajeb', 
    'El Panama', 
    'Elbasan', 
    'Erasmia', 
    'Erebuni Fortress', 
    'Escapaes', 
    'Esteli', 
    'Etunda', 
    'Faaborg', 
    'Fajardo', 
    'Famagusta', 
    'Fasa', 
    'Ferizaj', 
    'Fianarantsoa', 
    'Filippiada', 
    'Finnoy', 
    'Fish Town', 
    'Floreal', 
    'Flying Fish Cove', 
    'Forte', 
    'Frandefors', 
    'Frederiksted', 
    'Freetown', 
    'Fuernitz', 
    'Funafuti', 
    'Fuzine', 
    'Gaborone', 
    'Gaozhongyicun', 
    'Gasparillo', 
    'Gelang Patah', 
    'George Hill', 
    'George Town', 
    'Georgetown', 
    'Geraardsbergen', 
    'Gibraltar', 
    'Giraltovce', 
    'GoÅ‚dap', 
    'Godby', 
    'Gouyave', 
    'Grand Cul-de-Sac', 
    'Grindavik', 
    'Grootfontein', 
    'Grytviken', 
    'Guadalupe', 
    'Guatemala City', 
    'Guntur', 
    'Gustavia', 
    'Guyton', 
    'Haage', 
    'Hacienda La Palma', 
    'HagÃ¥tÃ±a', 
    'Hajom', 
    'Hamilton', 
    'Harare', 
    'Hargeysa', 
    'Hasle', 
    'Hell', 
    'Herat', 
    'Hespeler', 
    'Higashine', 
    'Hillcrest', 
    'Hlaing', 
    'Hlinik', 
    'Hohne', 
    'Holland Village', 
    'Home', 
    'Honeymoon Bay', 
    'Honiara', 
    'Horki', 
    'Hornbaek', 
    'Huacho', 
    'Huaral', 
    'Hucisko Jawornickie', 
    'Hvalba', 
    'Hyoja-dong', 
    'Ialoveni', 
    'Ichinomiya', 
    'Ijevan', 
    'Ikotun', 
    'Il-Pergla', 
    'Innan Glyvur', 
    'Ivankov', 
    'Jaguariaiva', 
    'Jamestown', 
    'Janderup', 
    'Jaszapati', 
    'Javhlant', 
    'Jenin', 
    'Jericho', 
    'Jinotega', 
    'Juba', 
    'Jumeauville', 
    'Kaarma', 
    'Kabi', 
    'Kabul', 
    'Kampala', 
    'Kampung Batu Kikir', 
    'Kanokupolu', 
    'Kaolack', 
    'Kapisillit', 
    'Karamay', 
    'Kathmandu', 
    'Kaunas', 
    'KeflavÃ­k', 
    'Khartoum', 
    'Khorugh', 
    'Kigali', 
    'Kiltamagh', 
    'Kingston', 
    'Kinshasa', 
    'Kisii', 
    'Kitwe', 
    'Klundert', 
    'Koskenkorva', 
    'Kouba', 
    'Kourou', 
    'Krapina', 
    'Kuala Belait', 
    'Kuala Kangsar', 
    'Kuantan', 
    'Kumba', 
    'Kuusalu', 
    'Kuwait City', 
    'Kwekwe', 
    'La Chaloupe Saint-Leu', 
    'La Victoria', 
    'Lagos de Moreno', 
    'Lakselv', 
    'Laoag', 
    'Las Piedras', 
    'Le Carbet', 
    'Le Gros-Morne', 
    'Le Morne-Rouge', 
    'Les Trois-Ilets', 
    'Level', 
    'Likasi', 
    'Lilongwe', 
    'Livingstone', 
    'Llanelli', 
    'Lodingen', 
    'Loltong', 
    'LomÃ©', 
    'Longyearbyen', 
    'Lorenfallet', 
    'Lourdes', 
    'Ludanice', 
    'Lukovit', 
    'Lumeje', 
    'Lykovrysi', 
    'Lyttelton', 
    'Macao', 
    'Macas', 
    'Machakos', 
    'Madaba', 
    'Madina Kokoun', 
    'Mahina', 
    'Majuro', 
    'Makola South', 
    'MalÃ©', 
    'Malabo', 
    'Mamagnia', 
    'Mamou', 
    'Manawi', 
    'Mandalay', 
    'Manouba', 
    'Manzini', 
    'Maputo', 
    'Marand', 
    'Marchin', 
    'Mariehamn', 
    'Marigot', 
    'MarijampolÄ—', 
    'Masaya', 
    'Maseru', 
    'Massaguet', 
    'Matola', 
    'Massaguet', 
    'Matola', 
    'Matraszolos', 
    'Mbabane', 
    'Mega', 
    'Menongue', 
    'Merzifon', 
    'Middelburg', 
    'Minsk', 
    'Minusinsk', 
    'Minya', 
    'Miraflores', 
    'Miranda', 
    'Misratah', 
    'Mito-shi', 
    'Mitrovica', 
    'Moholm', 
    'Molah', 
    'Monaco', 
    'Moneague', 
    'Mont-Dore', 
    'Montevideo', 
    'Morne-a-l\'Eau', 
    'Morogoro', 
    'Moroni', 
    'Moutsamoudou', 
    'Mufakose', 
    'Muscat', 
    'Myggenas', 
    'Nacimiento', 
    'Nagashima', 
    'Nagykoru', 
    'Naifaru', 
    'Nakhon Sawan', 
    'Nampula', 
    'Narathiwat', 
    'Nassau', 
    'Navacerrada', 
    'Negara', 
    'Negril', 
    'Neiafu', 
    'Nendeln', 
    'Neuhausen', 
    'Neves', 
    'New Amsterdam', 
    'Newlands', 
    'Newry', 
    'Nghi Loc', 
    'Niamey', 
    'Nieuw Amsterdam', 
    'Niulanshan', 
    'Nizwa', 
    'Noormarkku', 
    'Northland', 
    'Nouakchott', 
    'Noumea', 
    'Novi Belgrade', 
    'Nuuk', 
    'Nyala', 
    'Nyarugunga', 
    'Ocotal', 
    'OEdkarby', 
    'Old Road', 
    'Ondangwa', 
    'Ouagadougou', 
    'Over Back The Damp', 
    'Owerri', 
    'Paamiut', 
    'Pago Pago', 
    'Paide', 
    'Paippinen', 
    'Paita', 
    'Panaga', 
    'Paradera', 
    'Parham', 
    'Paro', 
    'Peel', 
    'Petit Cayenne', 
    'Petran', 
    'Philipsburg', 
    'Phumi Boeng (1)', 
    'Phumi Chhuk', 
    'Phumi Prei', 
    'Phumi Siem Reab', 
    'Phuntsholing', 
    'Pikermi', 
    'Piri', 
    'Pirot', 
    'Planken', 
    'Pobeda', 
    'Pocklington', 
    'Pongani', 
    'Port Louis', 
    'Port Mathurin', 
    'Port Vila', 
    'Port-aux-Francais', 
    'Port-Louis', 
    'Praia', 
    'Pristina', 
    'Pucallpa', 
    'Puchong Batu Dua Belas', 
    'Pugliano', 
    'Pugwash', 
    'Purbalingga', 
    'Pyongyang', 
    'Quatre Bornes', 
    'Quelimane', 
    'Quito', 
    'Rabat', 
    'Rawai', 
    'Remire-Montjoly', 
    'Ribeira do Pombal', 
    'Rio Blanco', 
    'Riohacha', 
    'Rizhao', 
    'Roma', 
    'Rose Hill', 
    'Rosia', 
    'Roskilde', 
    'Rothbury', 
    'Ruutana', 
    'Ruwi', 
    'SÃ£o TomÃ©', 
    'Sabaneta', 
    'Sada', 
    'Safotulafai', 
    'Sahab', 
    'Saham', 
    'Sai Keng', 
    'Saignelegier', 
    'Saint George', 
    'Saint Helier', 
    'Saint Peter', 
    'Saint-Domet', 
    'Saint-Francois', 
    'Sainte-Anne', 
    'Saipan', 
    'Salalah', 
    'Salem', 
    'Saltvik', 
    'Samad', 
    'Samarkand', 
    'San Antonio Miramar', 
    'San Bernardo', 
    'San Diego', 
    'San Fernando', 
    'San Jose Pinula', 
    'San Juan', 
    'San Juan del Sur', 
    'San Lazzaro degli Armeni', 
    'San Marcos', 
    'San Miguelito', 
    'Sana\'', 
    'Sanad', 
    'Sancti SpÃ­ritus', 
    'Sandrovo', 
    'Sansanne-Mango', 
    'Santa Coloma de Gramenet', 
    'Santa Cruz', 
    'Santa Rita', 
    'Santo Domingo', 
    'Santry', 
    'Sao Mamede de Infesta', 
    'Satu Mare', 
    'Savannah', 
    'Savitaipale', 
    'Schaan', 
    'Selfoss', 
    'Serang', 
    'Serangoon', 
    'Serravalle', 
    'Shar', 
    'Shek\'vetili', 
    'Shepshed', 
    'Sidon', 
    'Sieradz', 
    'Sint Nicolaas', 
    'Solwezi', 
    'Somerset', 
    'Sonaly', 
    'Sonsonate', 
    'Soroca', 
    'Southwick', 
    'Spetisbury', 
    'Sprundel', 
    'St Peter Port', 
    'St. George\'s', 
    'Stanley', 
    'Stara Pazova', 
    'Stieglitz', 
    'Stokkseyri', 
    'Suncheon', 
    'Suva', 
    'Syeverodonets\'k', 
    'Taipa', 
    'Taitung', 
    'Takamaka', 
    'Talarn', 
    'Tamano', 
    'Tamarin', 
    'Tan Binh', 
    'Tanjung Sepat', 
    'Tara', 
    'Tatarusi', 
    'Taza', 
    'Tema', 
    'The Garden', 
    'The Valley', 
    'Thimphu', 
    'Thirumangalam', 
    'Titikaveka', 
    'Toila', 
    'Toledo', 
    'Torteval', 
    'Tripoli', 
    'Tristan Da Cunha', 
    'Truong Son', 
    'Ts\'khinvali', 
    'Tunis', 
    'Turbo', 
    'Turdera', 
    'Turrucares', 
    'Tutong', 
    'Ufa', 
    'Ukmerge', 
    'Ulan Bator', 
    'Umwa Village', 
    'Undurkhaan', 
    'Union', 
    'Upernavik', 
    'Ust\'-Labinsk', 
    'Utsjoki', 
    'Vacoas', 
    'Vailala', 
    'Vaj', 
    'Valga', 
    'Vance', 
    'Vastra Ramlosa', 
    'Vatican City', 
    'Veles', 
    'Vientiane', 
    'ViesÄ«te', 
    'Vievis', 
    'Villa Regina', 
    'Villanueva', 
    'Villarrica', 
    'Villars-sur-Ollon', 
    'Vinkovci', 
    'Vitebsk', 
    'Vostok', 
    'Vredeberg', 
    'Wa', 
    'Waitakere City', 
    'Walvis Bay', 
    'Wan Tsai', 
    'Wang Thonglang', 
    'Wazir Akbar Khan', 
    'West Island', 
    'Westleton', 
    'Willemstad', 
    'Winschoten', 
    'YaoundÃ©', 
    'Yap', 
    'Zaslawye', 
    'Zastava', 
    'Zgornje Gorje', 
    'Zhenhua', 
    'Zibreira', 
    'Zurges',
    'sanFrancisco',
    'seattle',
    'omaha',
    'lasVegas',
    'newYork',
    'portland',
    'austin',
    'losAngeles',
    'chicago',
    'phoenix',
    'philadelphia',
    'sanAntonio',
    'sanDiego',
    'dallas',
    'sanJose',
    'jacksonville',
    'columbus',
    'indianapolis',
    'fortWorth',
    'charlotte',
    'denver',
    'elPaso',
    'washingtonDC',
    'boston',
    'detroit',
    'nashville',
    'memphis',
    'oklahomaCity',
    'louisville',
    'baltimore',  
   ] 
}